### PR TITLE
Tx confirmations bug

### LINKED ISSUE #712: Scanner didn't confirm transaction
Problematic TX: https://live.blockcypher.com/btc/tx/e2b3a88d8ef0aa39289b038ffdb2a9df2af75e63f2788bb14c41793dbb81644a/

1. Check that indexers have blocks for the tx.
2. Check operation of scanner for new blocks.

### PR DESCRIPTION
**Pull request by fastpok**
Temporary fixes #712 by disabling broadcasting new filters on the server side.
Also fixes sync status bug where "Current height is x" is displayed instead of "Synced".

### CODE REVIEW

File: index-server/src/Ergvein/Index/Server/TCPService/Server.hs [hunk 1]
```diff
@@ -107,7 +107,7 @@ runConnection (sock, addr) = incGaugeWhile activeConnsGauge $ do
       -- Spawn message sender thread
       fork $ sendLoop sendChan
       -- Spawn broadcaster loop
-      fork $ broadcastLoop sendChan
+      -- fork $ broadcastLoop sendChan
```
Comment (NCrashed) [inline index-server/src/Ergvein/Index/Server/TCPService/Server.hs:110]: Add url to the PR

**Review by NCrashed — CHANGES_REQUESTED** [review]

**Review by NCrashed — APPROVED** [review]
