### PR TITLE
Height tracking fix

### LINKED ISSUE #1036: Transaction confirmation is displayed with a delay
in the wallet, the confirmation of transactions may lag by several blocks

### PR DESCRIPTION
**Pull request by fastpok**
Fixes #1036

### CODE REVIEW

File: ergvein-core/src/Ergvein/Core/Node/Btc/Headers.hs [hunk 1]
```diff
@@ -44,10 +44,12 @@ addHeader t bh tree@HeadersTree{..} = case getBestBlock of
       M.lookup bestHash headersNodes
     getParentBlock = M.lookup (prevBlock bh) headersNodes
     theBest = case headersBest of
```
Comment (NCrashed) [inline ergvein-core/src/Ergvein/Core/Node/Btc/Headers.hs:46]: Perhaps we can try there more elegant form via do notation:
``` haskell
    theBest = fromMaybe (headerHash bh) $ do
      curBestHash <- headersBest
      curBest <- M.lookup curBestHash headersNodes
      pure $ fromMaybe curBestHash $ do
        bhParent <- M.lookup (prevBlock bh) headersNodes
        pure $ if nodeWork curBest < nodeWork bhParent + headerWork bh
          then headerHash bh
          else curBestHash
```

**Review by NCrashed — CHANGES_REQUESTED** [review]

**Review by NCrashed — APPROVED** [review]
