### PR TITLE
Utxo bug 840

### LINKED ISSUE #840: Wallet restore results in incorrect UTXO set
After restoring the wallet, the wrong balance is displayed

image_2021-02-04_02-56-33

The right balance is displayed on the last tx info page

image_2021-02-04_02-56-52

The reason is incorrect calculation of UTXOs during restore process. Spent outputs are treated as unspent

### PR DESCRIPTION
**Pull request by NCrashed**
Fix #840. The issue was that we added batches for blocks, but forgot to check utxos spending across transactions over all transactions in several blocks over whole batch.

### CODE REVIEW

File: wallet/src/Ergvein/Wallet/Scan.hs [hunk 1]
```diff
@@ -196,43 +196,53 @@ getTxsToRemove confirmedTxIds possiblyReplacedTxs =
...
 
+makeTxsMap :: M.Map HB.BlockHash HB.BlockHeight -> HB.Block -> Map TxHash EgvTx
+makeTxsMap heights block = M.fromList . fmap (\tx -> (mkTxId tx, TxBtc $ BtcTx tx mheha)) $ txs
+  where
+    txs = HB.blockTxns block
+    mkTxId = hkTxHashToEgv . HT.txHash
+    blockTime = secToTimestamp . HB.blockTimestamp . HB.blockHeader $ block
+    bhash = HB.headerHash . HB.blockHeader $ block
+    mh = Just $ maybe 0 fromIntegral $ M.lookup bhash heights
+    mheha = (\h -> EgvTxMeta (Just h) (Just bhash) blockTime) <$> mh
```
Comment (fastpok) [inline wallet/src/Ergvein/Wallet/Scan.hs:207]: `mheha` seems like a typo, probably you meant `meta`
